# This is where you can adjust all the amazing settings for this plugin!
# You can use custom colors by using an '&' except on custom product names
# Custom products: "Name in caps | price | custom name for product"
# Adjust messages to your liking!
# Dealers stores the uuids of your dealers.
# Don't change the config version!

version: 1.0
messages:
  moneyReceived: 'You have earned $%money% from selling your product!'
inventory name: 'Place your product in!'
products:
- 'SUGAR 1.00 Cocaine'
- 'LONG_GRASS 1.00 Weed'
- 'RABBIT_STEW 10.00 Heroine'
- 'BROWN_MUSHROOM 5.00 Shrooms'
dealers: []